title: 암껏도 하지 마
description: bundle exec jekyll install
author: 자무카
avatar: /logo.png
email: htmsejong@gmail.com

# skin: solarized

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
twitter:
  username: ksunghun
  card: summary
logo: logo.png
social:
  name: 강뚜뚜
  links:
    - https://twitter.com/ksunghyun
    - https://www.facebook.com/htmsejong
    - https://github.com/ngzhio
    - https://github.com/nodo1014
google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: ko
