[build]
  publish = "_site"
  command = "bundle install && bundle exec jekyll build"

[build.environment]
  RUBY_VERSION = "3.1.0"
  JEKYLL_ENV = "production"

[context.deploy-preview.environment]
  JEKYLL_ENV = "development"

[context.branch-deploy.environment]
  JEKYLL_ENV = "development" 